openapi: 3.0.0
info:
  title: Libo
  version: '1.0'
servers:
  - url: 'https://demo.libo.lumibib.ch/api/v1'
    description: Demo
paths:
  /products:
    parameters: []
    get:
      summary: Get products
      tags: []
      responses:
        '200':
          description: Products Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
              examples: {}
        '404':
          description: Product Not Found
      operationId: get-users-userId
      description: Retrieve the information of the user with the matching user ID.
  /events:
    get:
      summary: Get events
      tags: []
      responses: {}
      operationId: get-events
      parameters:
        - schema:
            type: string
            example: fr
          in: query
          name: l
          description: Locale
        - schema:
            type: string
          in: query
          name: 'filter[field]'
          description: Filtering by field name
          style: form
        - schema:
            type: string
          in: query
          name: sort
          description: Sorting by field name
        - schema:
            type: string
          in: query
          name: page
        - schema:
            type: string
          in: query
          name: limit
      x-internal: false
components:
  schemas:
    Product:
      title: Product
      type: object
      properties:
        id:
          type: string
